# Generated by Django 4.2.7 on 2026-01-04 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstimationSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_label', models.CharField(blank=True, max_length=200)),
                ('object_summary', models.TextField(blank=True)),
                ('object_json', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('QUESTIONS_ASKED', 'Questions Asked'), ('IN_PROGRESS', 'In Progress'), ('ESTIMATED', 'Estimated'), ('FAILED', 'Failed')], default='QUESTIONS_ASKED', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='media_store.uploadedimage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimation_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('text', models.TextField()),
                ('answer_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('boolean', 'Boolean'), ('select', 'Select')], default='text', max_length=16)),
                ('unit', models.CharField(blank=True, max_length=32)),
                ('options', models.JSONField(blank=True, default=list)),
                ('required', models.BooleanField(default=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='estimation_sessions.estimationsession')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value_text', models.TextField(blank=True)),
                ('value_number', models.FloatField(blank=True, null=True)),
                ('value_boolean', models.BooleanField(blank=True, null=True)),
                ('value_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='estimation_sessions.question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='estimation_sessions.estimationsession')),
            ],
            options={
                'unique_together': {('session', 'question')},
            },
        ),
    ]
