# Generated by Django 4.2.7 on 2026-01-25 11:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estimation_sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BMICategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('min_bmi', models.FloatField()),
                ('max_bmi', models.FloatField()),
                ('description', models.TextField()),
                ('recommendation', models.TextField()),
                ('color_code', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'BMI Categories',
                'ordering': ['min_bmi'],
            },
        ),
        migrations.CreateModel(
            name='BreedReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(help_text='dog, cat, rabbit, etc.', max_length=50)),
                ('breed', models.CharField(max_length=100)),
                ('aliases', models.JSONField(blank=True, default=list, help_text='Alternative breed names')),
                ('puppy_min_kg', models.FloatField(blank=True, null=True)),
                ('puppy_max_kg', models.FloatField(blank=True, null=True)),
                ('adult_min_kg', models.FloatField()),
                ('adult_max_kg', models.FloatField()),
                ('senior_min_kg', models.FloatField(blank=True, null=True)),
                ('senior_max_kg', models.FloatField(blank=True, null=True)),
                ('underweight_threshold', models.FloatField(default=0.85, help_text='Below 85% of ideal = underweight')),
                ('overweight_threshold', models.FloatField(default=1.15, help_text='Above 115% of ideal = overweight')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['species', 'breed'],
                'unique_together': {('species', 'breed')},
            },
        ),
        migrations.CreateModel(
            name='FoodNutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('aliases', models.JSONField(blank=True, default=list, help_text='Alternative names for fuzzy matching')),
                ('calories_per_100g', models.FloatField()),
                ('protein_per_100g', models.FloatField(default=0)),
                ('carbs_per_100g', models.FloatField(default=0)),
                ('fat_per_100g', models.FloatField(default=0)),
                ('fiber_per_100g', models.FloatField(default=0)),
                ('food_category', models.CharField(blank=True, help_text='fruit, vegetable, meat, dairy, etc.', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Food Nutrition Data',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ShippingCarrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('service_type', models.CharField(help_text='Ground, Express, Overnight, etc.', max_length=50)),
                ('base_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_weight_kg', models.FloatField()),
                ('volumetric_divisor', models.IntegerField(default=5000, help_text='Divisor for volumetric weight (L×W×H)/divisor')),
                ('is_international', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name', 'service_type'],
            },
        ),
        migrations.CreateModel(
            name='WeightEstimate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value_grams', models.FloatField()),
                ('min_grams', models.FloatField()),
                ('max_grams', models.FloatField()),
                ('confidence', models.FloatField(default=0.3)),
                ('unit_display', models.CharField(default='g', max_length=16)),
                ('rationale', models.TextField(blank=True)),
                ('raw_json', models.JSONField(blank=True, default=dict)),
                ('category', models.CharField(choices=[('food', 'Food'), ('package', 'Package'), ('pet', 'Pet'), ('person', 'Person'), ('general', 'General')], default='general', max_length=20)),
                ('category_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estimate', to='estimation_sessions.estimationsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeightFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_weight_grams', models.FloatField()),
                ('accuracy_rating', models.IntegerField(blank=True, help_text='1-5 star rating', null=True)),
                ('user_notes', models.TextField(blank=True)),
                ('helpful', models.BooleanField(default=True, help_text='Was this estimation helpful?')),
                ('error_grams', models.FloatField(blank=True, null=True)),
                ('error_percentage', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('estimate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='estimates.weightestimate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PetEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=50)),
                ('breed', models.CharField(blank=True, max_length=100)),
                ('age_category', models.CharField(blank=True, help_text='puppy, adult, senior', max_length=20)),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('is_neutered', models.BooleanField(blank=True, null=True)),
                ('health_status', models.CharField(blank=True, help_text='underweight, healthy, overweight', max_length=20)),
                ('ideal_weight_min', models.FloatField(blank=True, null=True)),
                ('ideal_weight_max', models.FloatField(blank=True, null=True)),
                ('weight_recommendation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('breed_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estimates.breedreference')),
                ('estimate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pet_details', to='estimates.weightestimate')),
            ],
        ),
        migrations.CreateModel(
            name='PackageEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length_cm', models.FloatField(blank=True, null=True)),
                ('width_cm', models.FloatField(blank=True, null=True)),
                ('height_cm', models.FloatField(blank=True, null=True)),
                ('volumetric_weight_g', models.FloatField(blank=True, null=True)),
                ('chargeable_weight_g', models.FloatField()),
                ('estimated_shipping_costs', models.JSONField(default=dict, help_text='Dictionary of carrier: cost')),
                ('is_fragile', models.BooleanField(default=False)),
                ('destination_type', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('estimate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='package_details', to='estimates.weightestimate')),
            ],
        ),
        migrations.CreateModel(
            name='FoodEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_calories', models.FloatField()),
                ('estimated_protein', models.FloatField(default=0)),
                ('estimated_carbs', models.FloatField(default=0)),
                ('estimated_fat', models.FloatField(default=0)),
                ('estimated_fiber', models.FloatField(default=0)),
                ('is_cooked', models.BooleanField(default=False)),
                ('portion_status', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('estimate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='food_details', to='estimates.weightestimate')),
                ('food_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estimates.foodnutrition')),
            ],
        ),
        migrations.CreateModel(
            name='BodyCompositionEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height_cm', models.FloatField()),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('activity_level', models.CharField(blank=True, max_length=50)),
                ('bmi', models.FloatField()),
                ('bmi_category', models.CharField(max_length=20)),
                ('ideal_weight_min_kg', models.FloatField()),
                ('ideal_weight_max_kg', models.FloatField()),
                ('body_fat_estimate', models.FloatField(blank=True, help_text='Estimated body fat percentage', null=True)),
                ('lean_mass_estimate', models.FloatField(blank=True, null=True)),
                ('health_recommendation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bmi_category_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estimates.bmicategory')),
                ('estimate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='body_details', to='estimates.weightestimate')),
            ],
        ),
    ]
