# Generated by Django 4.2.7 on 2026-01-04 19:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estimation_sessions', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeightEstimate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value_grams', models.FloatField()),
                ('min_grams', models.FloatField()),
                ('max_grams', models.FloatField()),
                ('confidence', models.FloatField(default=0.3)),
                ('unit_display', models.CharField(default='g', max_length=16)),
                ('rationale', models.TextField(blank=True)),
                ('raw_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estimate', to='estimation_sessions.estimationsession')),
            ],
        ),
    ]
